### PR TITLE
Removed duplicate Sass file

### PR DESCRIPTION
**Pull request by kittsville**
File exists under `\_sass\projects.scss`. I'm guessing the one under `_sass` is the one that's used as removing this one seems to have no effect on the site.

### CODE REVIEW

**Comment by kittsville** [comment]
Wait, my bad. That file is definitely needed.

**Comment by ashutosh2k12** [comment]
I am little unsure. I think its needed. Will run tests

**Comment by kittsville** [comment]
I think I misunderstood how Sass files work in Jekyll. All the files in the `\_sass` are dependencies that can be loaded in by other Sass files but aren't compiled into CSS themselves. It's Sass files elsewhere (e.g. `\static\css`) that get compiled into CSS.

The reason I didn't think it was necessary was because it had *already* been compiled into CSS on my machine so I could delete the Sass file without immediately feeling the consequences.

**Comment by ashutosh2k12** [comment]
Yes, the `_sass` only have partials. I mistakenly had `projects.scss` in `_sass` directory. Removed in [this commit](https://github.com/ashutosh2k12/hcz-jekyll-blog/commit/774a8624901f6791538c55f6752bb367abee76f7)

**Pull request merged**
